backend:
  name: github
  repo: federicociner/federicociner.com

media_folder: static/assets
public_folder: assets

media_library:
    name: cloudinary
    config:
        cloud_name: federicociner-com
        api_key: 319647146488792
        default_transformations:
            - - width: 50
                quality: auto
                dpr: auto

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
